# denylist.sh — the ONE never-touch list for every script that writes the vault.
#
# WHY IT IS A LIB. It started inside `cb-ingest` (`is_forbidden`, :59) because
# cb-ingest was the only script allowed to write. `cb-distill` now writes too,
# and a second copy of a security-relevant list is a copy that drifts: the day
# one of them gains `Confidential/` and the other doesn't, the weaker script is
# the whole gate. One list, sourced by both — a spec invariant, not a style
# preference.
#
# Sourced, never executed: no `set -e` here (it would leak into every caller and
# into bats `load`). Same house shape as paths.sh and land.sh.

# cb_is_forbidden PATH — 0 = NEVER write this, 1 = allowed by this gate.
#
# ⚠️ This is a DENYlist, so a 1 means only "not explicitly forbidden" — it is
# never on its own an authorization. Callers pair it with their own allowlist:
# cb-land refuses anything outside `00 Inbox/`, cb-distill anything outside the
# three roots §7's table names.
#
# Moved here from cb-ingest:59-66 — same cases, same order, same semantics — so
# `cb-ingest.bats` (which pins every one of these refusals) keeps passing
# untouched. The categories: identity and policy files, the fleet's own
# configuration, other people's records, anything Confidential, git internals,
# the scripts that enforce all of the above, and the two path shapes that escape
# the vault entirely.
#
# `*/CLAUDE.md` is the ONE addition to the moved list, and it closes a hole the
# root-only match left open. A directory `CLAUDE.md` is a rule surface in exactly
# the sense §7's table marks ❌ never — it is the conventions file that loads
# when an agent works in that directory, so rewriting one silently changes how
# every later agent behaves there. The bare `CLAUDE.md` case caught the repo root
# and nothing else, which left `03 Resources/CLAUDE.md` writable by a distiller
# whose allowlist covers `03 Resources/` (measured 2026-08-14: it returned
# "allowed"), and `02 Areas/platform/CLAUDE.md` the moment that root was added.
# It tightens `cb-ingest` too — correct, and strictly safer.
cb_is_forbidden() {
  case "$1" in
    CLAUDE.md|profile.md|personality.md|hot.md|board.md|magneto.md) return 0;;
    */CLAUDE.md) return 0;;                # a directory's conventions file, at any depth
    .claude/*|Confidential/*|People/*|.git/*|scripts/*) return 0;;
    /*|*..*) return 0;;                    # absolute or traversal
  esac
  return 1
}

# cb_is_generated_surface PATH — 0 = this file has a dedicated fleet writer on a
# timer, 1 = it does not.
#
# THIS IS AN ATTRIBUTION RULE, NOT AN EXCEPTION LIST, and the difference is the
# whole reason it exists as its own predicate rather than a carve-out at a call
# site. `cb_is_forbidden` answers "may this be written?" and every path above
# still answers no, both writers included — this changes nothing about that.
# What it answers is a different question: "if this file just changed, WHO
# changed it?"
#
# For the hand-maintained half of the list — People/, Confidential/, .claude/,
# scripts/, .git/, profile.md, personality.md, and CLAUDE.md at any depth —
# nothing on this machine writes them on its own, so a change during a pass IS
# attributable to the pass, and refusing loudly is correct.
#
# The three below are the opposite: each is regenerated by a named process on
# its own cadence. `cb-board` rewrites `board.md` from every `cb-watch` tick
# (~30s), `hot.md` is the handoff snapshot, `magneto.md` the fleet's own board.
# A distill pass takes minutes, so churn in these files during one is evidence
# of their generator and never of the distiller — measured 2026-08-15: a routine
# `board.md` refresh mid-pass refused the whole `distill:` commit, which on a
# ~30s cadence would have made the nightly pass permanently non-functional.
# Inferring authorship from "this is dirty and out of bounds" is simply a false
# inference for these three, so the caller notes them and moves on.
cb_is_generated_surface() {
  case "$1" in
    hot.md|board.md|magneto.md) return 0;;
  esac
  return 1
}
